### ISSUE TITLE
会内存溢出啊。最近的版本。

### ISSUE THREAD

**Issue by hugbio** [qiniu/android-sdk#218]
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
    at java.lang.VMThread.create(Native Method)
    at java.lang.Thread.start(Thread.java:1029)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1338)
    at okhttp3.Dispatcher.enqueue(Dispatcher.java:112)
    at okhttp3.RealCall.enqueue(RealCall.java:78)
    at okhttp3.RealCall.enqueue(RealCall.java:70)
    at com.qiniu.android.http.Client.asyncSend(Client.java:161)
    at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:262)
    at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:234)
    at com.qiniu.android.storage.FormUploader.post(FormUploader.java:139)
    at com.qiniu.android.storage.FormUploader.upload(FormUploader.java:53)
    at com.qiniu.android.storage.UploadManager.put(UploadManager.java:144)
    at com.qiniu.android.storage.UploadManager.put(UploadManager.java:114)
    at com.ancda.registration.service.UpdataService.upImage(UpdataService.java:550)

**Comment by longbai** [comment]
请问有demo 么？ 具体哪个版本，这边单元测试是OK的。

**Comment by hugbio** [comment]
没有demo。是7.2.2版本。

**Comment by tengqiniu** [comment]
您那边使用我们的最新版本7.3.2看下呢，有什么问题也可以工单反馈给我们。
