### ISSUE TITLE
关于内存溢出问题。能否解决啊

### ISSUE THREAD

**Issue by hugbio** [qiniu/android-sdk#219]
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
    at java.lang.VMThread.create(Native Method)
    at java.lang.Thread.start(Thread.java:1029)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1338)
    at okhttp3.Dispatcher.enqueue(Dispatcher.java:112)
    at okhttp3.RealCall.enqueue(RealCall.java:78)
    at okhttp3.RealCall.enqueue(RealCall.java:70)
    at com.qiniu.android.http.Client.asyncSend(Client.java:165)
    at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:266)
    at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:238)
    at com.qiniu.android.storage.FormUploader.post(FormUploader.java:139)
    at com.qiniu.android.storage.FormUploader.upload(FormUploader.java:53)
    at com.qiniu.android.storage.UploadManager.put(UploadManager.java:144)
    at com.qiniu.android.storage.UploadManager.put(UploadManager.java:114)
    at com.ancda.registration.service.UpdataService.upImage(UpdataService.java:539)
    at com.ancda.registration.service.UpdataService.access$1300(UpdataService.java:64)
    at com.ancda.registration.service.UpdataService$UpImageThread.run(UpdataService.java:320)

由于需求原因需要在后台不断监控是否有图片。如果有图片会不断上传直到所有图片上次完毕。图片也会在需要的时候不断生成。所以我们应用会经常调用sdk的上传接口。但是最近我发现会有内存溢出的问题出现。如上的错误信息。
我这边每次上次都会重新new一个UploadManager对象。不知道是不是跟这个有关。请解答！

**Comment by longbai** [comment]
uploadmanager 对象 只要一个就好了，不需要重复new，因为底层的okhttp 每次创建 都要建立threadpool

**Comment by hugbio** [comment]
我猜可能就是i这样的。那这个是不是一个“bug”或者隐患。我觉得你们最好标一下说明。

**Comment by tengqiniu** [comment]
好的，这边会改进下，感谢您提供的宝贵意见。
