### ISSUE TITLE
一个用户一直上传失败，status:-1001，请问应该如何解决问题

### ISSUE THREAD

**Issue by dongorigin** [qiniu/android-sdk#264]
ResponseInfo={ver:7.3.3,ResponseInfo:1498643714294365,status:-1001, reqId:, xlog:, xvia:, host:up.qiniu.com, path:/, ip:, port:80, duration:-1.000000 s, time:1498643834, sent:-1,error:null}  
response=null  
更多日志  
```
06-28 17:57:14.379 W/System.err(27737): java.net.SocketTimeoutException
06-28 17:57:14.380 W/System.err(27737): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
06-28 17:57:14.380 W/System.err(27737): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
06-28 17:57:14.380 W/System.err(27737): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
06-28 17:57:14.380 W/System.err(27737): 	at okio.o$2.read(Okio.java:138)
06-28 17:57:14.380 W/System.err(27737): 	at okio.a$2.read(AsyncTimeout.java:236)
06-28 17:57:14.380 W/System.err(27737): 	at okio.s.a(RealBufferedSource.java:325)
06-28 17:57:14.381 W/System.err(27737): 	at okio.s.a(RealBufferedSource.java:314)
06-28 17:57:14.381 W/System.err(27737): 	at okio.s.u(RealBufferedSource.java:210)
06-28 17:57:14.381 W/System.err(27737): 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
06-28 17:57:14.381 W/System.err(27737): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
06-28 17:57:14.381 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-28 17:57:14.381 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-28 17:57:14.381 W/System.err(27737): 	at com.qiniu.android.http.Client$2.intercept(Client.java:86)
06-28 17:57:14.381 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-28 17:57:14.381 W/System.err(27737): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
06-28 17:57:14.382 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-28 17:57:14.383 W/System.err(27737): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-28 17:57:14.383 W/System.err(27737): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
06-28 17:57:14.383 W/System.err(27737): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
06-28 17:57:14.383 W/System.err(27737): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
06-28 17:57:14.383 W/System.err(27737): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-28 17:57:14.383 W/System.err(27737): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-28 17:57:14.383 W/System.err(27737): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by jemygraw** [comment]
这个是网络连接问题，检查下网络，重试看看。
