### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.qiniu.storage.Configuration.upHost(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by luddite1989** [qiniu/android-sdk#286]
升级到2.+后出现。

**Comment by JiongBull** [comment]
```java 
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.qiniu.android.storage.UpToken.token' on a null object reference
at com.qiniu.android.collect.UploadInfoCollector.upload(UploadInfoCollector.java:248)
at com.qiniu.android.collect.UploadInfoCollector.tryUploadAndClean(UploadInfoCollector.java:233)
at com.qiniu.android.collect.UploadInfoCollector.access$200(UploadInfoCollector.java:26)
at com.qiniu.android.collect.UploadInfoCollector$2.run(UploadInfoCollector.java:207)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
``` 
7.3.10 大量出现。

**Comment by JiongBull** [comment]
7.3.9 没问题，7.3.10 上传时先使用一个空token，下次上传再使用一个假的 token 会出现这个错误。
