### ISSUE TITLE
 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by linuxhsj** [qiniu/android-sdk#287]
遇到一个必现的bug
`  java.lang.NoSuchMethodError: No virtual method startsWith(Lokio/ByteString;)Z in class Lokio/ByteString; or its super classes (declaration of 'okio.ByteString' appears in /data/app/cn.machat.im-2/base.apk:classes18.dex)
                                                at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:511)
                                                at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
                                                at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:127)
                                                at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:230)
                                                at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:205)
                                                at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:106)
                                                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:46)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                at com.qiniu.android.http.Client$2.intercept(Client.java:86)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                at java.lang.Thread.run(Thread.java:818)`
@lidaobing @why404 @xushiwei @hughlv @SunRunAway

**Comment by ReikyZ** [comment]
用的什么版本的sdk包？以及什么版本的okhhttp？
