### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by Joy-Whale** [qiniu/android-sdk#292]
我在Junit中模拟图片上传，使用服务器java sdk生成的token上传，返回错误：
```
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:566)
	at com.qiniu.android.storage.UpToken.parse(UpToken.java:36)
	at com.qiniu.android.storage.UploadManager.put(UploadManager.java:159)
	at com.qiniu.android.storage.UploadManager.put(UploadManager.java:145)
```
看了下源码，发生在UpToken parse这个方法中，即是无效的token？

服务端的源码如下
```
        // 生成上传凭证，然后准备上传
	String accessKey = "我们的accessKay";
	String secretKey = "我们的secretKey"";
	String bucket = "beebee-test";
	Auth auth = Auth.create(accessKey, secretKey);
	String upToken = auth.uploadToken(bucket);
	System.out.print(upToken);
```
请问这是什么原因造成的？

**Comment by Joy-Whale** [comment]
我的上传代码如下：
               ```
String token = "从服务端获取的token";
		new UploadManager().put("D:\\test.jpg", null, token, (key, info, response) -> {
			if (info.isOK()) {
				System.err.print(response.toString());
			} else {
				System.err.print(info + "\n\r" + response);
			}
		}, null);
```

**Comment by Joy-Whale** [comment]
生成的token 用java sdk上传是可以上传成功的

**Comment by jemygraw** [comment]
null pointer的错误很好找，自己打个断点就可以发现问题了
