### ISSUE TITLE
Unexpected char 0x821e at 34 in Content-Disposition value: form-data; name="file"; filename="中文文件名"

### ISSUE THREAD

**Issue by xiaoxiaoying** [qiniu/android-sdk#311]
0：Chinese file name
1：The file size is less than the shard upload size
java.lang.IllegalArgumentException: Unexpected char 0x54c8 at 34 in Content-Disposition value: form-data; name="file"; filename="哈哈.mp4"
        at okhttp3.Headers.checkValue(Headers.java:272)
        at okhttp3.Headers.of(Headers.java:224)
        at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:259)
        at okhttp3.MultipartBody$Builder.addFormDataPart(MultipartBody.java:324)
        at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:308)
        at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:292)
        at com.qiniu.android.storage.FormUploader.post(FormUploader.java:163)
        at com.qiniu.android.storage.FormUploader.upload(FormUploader.java:57)
        at com.qiniu.android.storage.UploadManager$2.onSuccess(UploadManager.java:170)
        at com.qiniu.android.common.AutoZone$1.complete(AutoZone.java:90)
        at com.qiniu.android.http.Client$3.run(Client.java:184)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7022)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

error: Line 74 of the FormUploader.class 
  if (k != null) {
            params.put("key", key);
            args.fileName = key;
        } else {
            args.fileName = "?";
        }

        // data is null , or file is null
        if (file != null) {
            args.fileName = file.getName();
        }
key is not work and filename set twice

**Comment by mzhkby** [comment]
@xiaoxiaoying 你这种情况是怎么解决的？

**Comment by xiaoxiaoying** [comment]
> @xiaoxiaoying 你这种情况是怎么解决的？

调换位置 

// data is null , or file is null
        if (file != null) {
            args.fileName = file.getName();
        }
        if (k != null) {
            params.put("key", key);
            args.fileName = key;
        } else {
            args.fileName = "?";
        }

**Comment by Howard-mo** [comment]
没看明是怎么样解决的呢

**Comment by xiaoxiaoying** [comment]
@Howard-mo 判断 file != null 放 k != null 前面
