### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: No static method get(Ljava/lang/String;)Lokhttp3/MediaType; in class Lokhttp3/MediaType

### ISSUE THREAD

**Issue by Yexiangxu** [qiniu/android-sdk#325]
Caused by: java.lang.NoSuchMethodError: No static method get(Ljava/lang/String;)Lokhttp3/MediaType; in class Lokhttp3/MediaType; or its super classes (declaration of 'okhttp3.MediaType' appears in /data/app/xxx.apk:classes2.dex)
        at com.qiniu.android.http.MultipartBody.<init>(MultipartBody.java:83)
        at com.qiniu.android.http.MultipartBody$Builder.build(MultipartBody.java:348)
        at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:318)
        at com.qiniu.android.http.Client.asyncMultipartPost(Client.java:293)
        at com.qiniu.android.storage.FormUploader.post(FormUploader.java:161)
        at com.qiniu.android.storage.FormUploader.upload(FormUploader.java:55)
        at com.qiniu.android.storage.UploadManager$2.onSuccess(UploadManager.java:170)

**Comment by liuchuanbao** [comment]
请问作者解决了没有？

**Comment by zhangls2014** [comment]
这是 okhttp 的兼容问题，要么就降级，要么就等更新

**Comment by liuchuanbao** [comment]
1，//    //上传到7牛服务器
    implementation('com.qiniu:qiniu-android-sdk:7.3.0') 降级
2，查看随意jar包 使用
 implementation （“jar”）{
        exclude group: 'com.squareup.okhttp3'
    }
3，删除所有项目中引用okio的的jar库（低版本的okhttp3需要配合okio，而高版本的okhttp3里面自带okio）

**Comment by blusewang** [comment]
被坑到了！发布了才知道有这出！

**Comment by BLiYing** [comment]
解决了吗

**Comment by culturer** [comment]
碰到同样的问题

**Comment by JemyCheung** [comment]
升级到7.5.0已经解决，您试试 @Yexiangxu @liuchuanbao @blusewang @zhangls2014 @BLiYing
