### ISSUE TITLE
java.lang.IllegalArgumentException: no field 'segments' of type class  [Ljava.util.concurrent.ConcurrentHashMap$Segment

### ISSUE THREAD

**Issue by Wenlong-Guo** [qiniu/android-sdk#431]
机型 android 5.1 (22)，OPPO:OPPO A37m:arm64-v8a
同样也发生在了 
android 6.0 (23)，LeEco:Le X620:arm64-v8a
android 6.0.1 (23)，Xiaomi:Redmi 4:arm64-v8a
android 5.1.1 (22)，OPPO:OPPO A53m:arm64-v8a
几个设备上

日志如下
`java.lang.IllegalArgumentException: no field 'segments' of type class [Ljava.util.concurrent.ConcurrentHashMap$Segment;
	at java.io.EmulatedFields.findMandatorySlot(EmulatedFields.java:188)
	at java.io.EmulatedFields.put(EmulatedFields.java:498)
	at java.io.EmulatedFieldsForDumping.put(EmulatedFieldsForDumping.java:154)
	at java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1235)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at com.qiniu.android.utils.StringUtils.toByteArray(StringUtils.java:3)
	at com.qiniu.android.http.DnsPrefetcher.startPrefetchDns(DnsPrefetcher.java:12)
	at com.qiniu.android.storage.UploadManager$4.run(UploadManager.java:1)
	at java.lang.Thread.run(Thread.java:818)
`

劳烦技术大佬给解决一下

**Comment by YangSen-qn** [comment]
@Wenlong-Guo  SDK 版本是多少呢？
