### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object

### ISSUE THREAD

**Issue by eshxcmhk** [qiniu/android-sdk#462]
依赖：``` com.qiniu:qiniu-android-sdk:8.3.0 ```
后台收到一个崩溃日志：
```
Process Name: 'com.qs.movementdetect'
Thread Name: 'Timer-0'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object reference
	at com.qiniu.android.utils.AndroidNetwork.getHostIP(AndroidNetwork.java:60)
	at com.qiniu.android.http.dns.DnsPrefetcher.prepareToPreFetch(DnsPrefetcher.java:140)
	at com.qiniu.android.http.dns.DnsPrefetcher.checkWhetherCachedDnsValid(DnsPrefetcher.java:121)
	at com.qiniu.android.http.dns.DnsPrefetchTransaction$3.run(DnsPrefetchTransaction.java:69)
	at com.qiniu.android.transaction.TransactionManager$Transaction.handleAction(TransactionManager.java:190)
	at com.qiniu.android.transaction.TransactionManager$Transaction.access$200(TransactionManager.java:130)
	at com.qiniu.android.transaction.TransactionManager.handleTransaction(TransactionManager.java:101)
	at com.qiniu.android.transaction.TransactionManager.handleAllTransaction(TransactionManager.java:93)
	at com.qiniu.android.transaction.TransactionManager.timerAction(TransactionManager.java:125)
	at com.qiniu.android.transaction.TransactionManager.access$300(TransactionManager.java:12)
	at com.qiniu.android.transaction.TransactionManager$1.run(TransactionManager.java:113)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
Back traces ends.
```

**Comment by YangSen-qn** [comment]
感谢反馈

**Comment by eshxcmhk** [comment]
设备信息:
```
设备机型: OPPO
是否Root: 否
机型版本: PDPM00
系统版本: android 11
设备电量: 83
电池温度: 403
磁盘可用占比: 39.25
内存可用占比: 4.35
CPU架构: arm64-v8a,armeabi-v7a,armeabi
```
```
设备机型: HUAWEI
是否Root: 否
机型版本: ELS-AN00
设备电量: 83
电池温度: 440
磁盘可用占比: 54.13
内存可用占比: 7.36
SD卡可用占比: --
CPU架构: arm64-v8a,armeabi-v7a,armeabi
前后台状态: 前台
```

**Comment by YangSen-qn** [comment]
@eshxcmhk 请升级 8.3.1

**Comment by eshxcmhk** [comment]
> @eshxcmhk 请升级 8.3.1

Thanks a lot
